# Generated by Django 4.2.4 on 2023-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('details', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
