# Generated by Django 4.2.4 on 2023-08-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='Degree',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
