# Generated by Django 4.2.4 on 2023-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_universities_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='Eligible_Countreies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='funding_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
