# Generated by Django 4.2.4 on 2023-08-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_universities_eligible_countreies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='details',
        ),
    ]
